#!/bin/bash
date=$(date)
fech=$(date +%F)
hour=$(date +"%H%M")
declare -a arr=("usapi-us-apis-paymentmethodsthirdparty-payments" "usapi-us-apis-peoplethirdparty-customers" "usapi-us-apis-productsthirdparty-accounts" "usapi-us-apis-productsthirdparty-cards")
declare -a arr2=("glapi-global-apis-paymentmethods-payments" "glapi-global-apis-people-customers" "glapi-global-apis-products-accounts" "glapi-global-apis-products-cards")
for i in "${!arr[@]}"; do
   echo "#############INIT#############" >> ~/update_$fech.log
   cd /home/ec2-user
   repo=${arr[$i]}
   path=${arr2[$i]}
   cd $repo
   result=$(git pull)
   if [ $? != 0 ]; then
      echo "Error on GIT pull process" >> ~/update_$fech.log
      echo $date >> ~/update_$fech.log
      echo $repo >> ~/update_$fech.log
      exit
   else

      if [ "$result" == "Already up-to-date." ]; then
         echo "Nothing to do" >> ~/update_$fech.log
         echo $date >> ~/update_$fech.log
         echo $repo >> ~/update_$fech.log
      else
         cd /home/ec2-user/paas-toolbox/gen-raml2view/
         node cli.js -r /home/ec2-user/$repo/ -o ../gen-site/src/app/api/$path/api.html
         echo "Update" >> ~/update_$fech.log
         echo $date >> ~/update_$fech.log
         echo $repo >> ~/update_$fech.log
      fi
   fi
done
if [ "$hour" == "0000" ]; then
   tar -cvzf ~/update-log-$fech.tgz ~/update_$fech.log
else
   echo "aun no"
fi
